#!/usr/bin/env python3
"""Generate the DENSE, segmented cmdName() lookup + DAT phrase table for
isp_voice_command_names.spin2 from the durable catalog tools/cmdname_catalog.tsv.

Design: the command-ID space is split into maximal contiguous runs. Each 'real'
run (individually-named phrases) becomes a dense WORD array; cmdName() range-checks
cmdId and indexes the matching array with a base-offset subtraction. The custom
run (IDs 5..21) routes to customWord() -- the hand-authored registration hook, so
applications can supply their own trained phrases. Everything else returns
@nm_unknown. Entries are object-relative WORD offsets resolved at runtime with @@.

Usage:
  python3 tools/gen_cmdname_table.py            # print the generated block to stdout
  python3 tools/gen_cmdname_table.py --apply     # splice it into the .spin2 between markers
"""
import sys

CATALOG = "tools/cmdname_catalog.tsv"
SPIN = "src/isp_voice_command_names.spin2"
START_MARK = "' >>> GENERATED cmd-name table"
END_MARK = "' <<< END GENERATED cmd-name table"

id2phrase = {}
other_phrase = None
for line in open(CATALOG):
    line = line.rstrip("\n")
    if line.startswith("# other\t"):
        other_phrase = line.split("\t", 1)[1]
        continue
    if not line or line.startswith("#"):
        continue
    sid, ph = line.split("\t", 1)
    id2phrase[int(sid)] = ph

ID_MAX = max(id2phrase)

def cls(i):
    ph = id2phrase.get(i, other_phrase)
    if ph == "(custom)":
        return "custom"
    if ph == other_phrase:
        return "unknown"
    return "real"

runs = []
i = 0
while i <= ID_MAX:
    c = cls(i)
    j = i
    while j + 1 <= ID_MAX and cls(j + 1) == c:
        j += 1
    runs.append((i, j, c))
    i = j + 1

SPECIAL = {"(none)": "nm_none", "(custom)": "nm_custom", other_phrase: "nm_unknown"}
phrase2label, order = {}, []
def label_for(ph, idx):
    if ph not in phrase2label:
        phrase2label[ph] = SPECIAL.get(ph, "nm_%03d" % idx)
        order.append(ph)
        if len(phrase2label[ph]) > 30:
            sys.exit("label too long: " + phrase2label[ph])
    return phrase2label[ph]

for ph in ("(none)", "(custom)", other_phrase):
    if ph is not None:
        label_for(ph, 0)
for i in range(ID_MAX + 1):
    label_for(id2phrase.get(i, other_phrase), i)

dispatch, arrays = [], []
for lo, hi, c in runs:
    rng = "%d..%d" % (lo, hi)
    pad = " " * max(1, 10 - len(rng))
    if c == "unknown":
        continue
    if c == "custom":
        dispatch.append("    %s:%spStr := customWord(cmdId)" % (rng, pad))
        continue
    arr = "nmTbl_%d" % lo
    base = "" if lo == 0 else " - %d" % lo
    dispatch.append("    %s:%spStr := @@%s[cmdId%s]" % (rng, pad, arr, base))
    arrays.append((arr, lo, hi))

out = []
out.append("PUB cmdName(cmdId) : pStr")
out.append("'' Return a pointer to the human-readable phrase for a command-word ID (dense indexed table).")
out.append("''")
out.append("'' @param cmdId - command-word ID to look up")
out.append("'' @returns pStr - pointer to the phrase ((none) for 0, registered/(custom) for 5..21, (unknown) if unmapped)")
out.append("")
out.append("  pStr := @nm_unknown                                          ' default: ID-space gaps and out-of-range")
out.append("  case cmdId")
out += dispatch
out += ["", ""]
out.append("DAT ' ---- Command-Word Phrase Table (dense indexed) ----")
out.append("")
out.append("' One dense WORD array per contiguous ID run; cmdName() range-checks cmdId and indexes the")
out.append("' matching array (base-offset subtracted). Entries are object-relative WORD offsets, resolved")
out.append("' at runtime with @@. No storage is spent on the ID-space gaps; IDs 5..21 route to customWord().")
for arr, lo, hi in arrays:
    out.append("")
    out.append("%s ' IDs %d..%d" % (arr, lo, hi))
    for i in range(lo, hi + 1):
        out.append("            word    @%-14s ' %d" % (phrase2label[id2phrase[i]], i))
out.append("")
out.append("' ---- phrase strings (deduped) ----")
for ph in order:
    out.append('%-14s byte    "%s", 0' % (phrase2label[ph], ph))

block = "\n".join(out)

if "--catalog-md" in sys.argv:
    md = ["# DF2301Q Command-Word Catalog",
          "",
          "> GENERATED by `tools/gen_cmdname_table.py --catalog-md` from `tools/cmdname_catalog.tsv`. Do not hand-edit.",
          "",
          "The full built-in vocabulary the module recognizes. Applications react to the **ID**; include",
          "`isp_voice_command_names` and call `cmdName(id)` for the human phrase. IDs 5-21 are user-trained",
          "**custom** slots the application registers (see the User Guide). Gaps in the numbering are",
          "unmapped (`cmdName` returns `(unknown)`).",
          "",
          "| ID | Phrase |",
          "|---:|--------|"]
    emitted_custom = False
    for i in range(ID_MAX + 1):
        ph = id2phrase.get(i)
        if ph is None:
            continue
        if ph == "(custom)":
            if not emitted_custom:
                md.append("| 5-21 | *application-registered custom words* (`(custom)` until registered) |")
                emitted_custom = True
            continue
        md.append("| %d | %s |" % (i, ph))
    open("DOCs/COMMAND-CATALOG.md", "w").write("\n".join(md) + "\n")
    sys.stderr.write("wrote DOCs/COMMAND-CATALOG.md (%d ids)\n" % (ID_MAX + 1))
    sys.exit(0)

if "--apply" in sys.argv:
    t = open(SPIN).read()
    s = t.index(START_MARK)
    e = t.index(END_MARK)
    s_eol = t.index("\n", s) + 1
    t = t[:s_eol] + "\n" + block + "\n\n" + t[e:]
    open(SPIN, "w").write(t)
    sys.stderr.write("applied to %s\n" % SPIN)
else:
    sys.stdout.write(block + "\n")

total = sum(hi - lo + 1 for _, lo, hi in arrays)
sys.stderr.write("arrays=%d dense_entries=%d unique_phrases=%d ID_MAX=%d\n" %
                 (len(arrays), total, len(order), ID_MAX))
